LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE  = yes
RGB_MATRIX_DRIVER = WS2812

BOOTLOADER = atmel-dfu
